_target_: torch_seq_moo.tasks.nupack.NupackTask
objectives:
  - energy
  - explength
eval_pref: 
  - 0.5
  - 0.5
score_max:
  - 60
  - 1.0
regex_list: !!null
min_len: 30
max_len: 60
num_start_examples: 512
batch_size: 16
max_num_edits: null
max_ngram_size: 1
allow_len_change: True
max_score_per_dim: 16
