_target_: torch_seq_moo.tasks.regex.RegexTask
regex_list:
  - "(?=A)"
  - "(?=V)"
  - "(?=C)"
obj_dim: 3
log_prefix: regex
min_len: 16
max_len: 18
num_start_examples: 512
batch_size: 16
max_num_edits: null
max_ngram_size: 1
allow_len_change: True
max_score_per_dim: 16
eval_pref: [0.3, 0.4, 0.3]